insert into authors (id, first_name, last_name) values (1, 'Tommi', 'Ripper');
insert into authors (id, first_name, last_name) values (2, 'Carroll', 'Postians');
insert into authors (id, first_name, last_name) values (3, 'Delmore', 'Kohnert');
insert into authors (id, first_name, last_name) values (4, 'Drona', 'O''Shiel');
insert into authors (id, first_name, last_name) values (5, 'Libbie', 'Epilet');
insert into authors (id, first_name, last_name) values (6, 'Gilli', 'Jantot');
insert into authors (id, first_name, last_name) values (7, 'Leonanie', 'Arblaster');
insert into authors (id, first_name, last_name) values (8, 'Danni', 'Keyson');
insert into authors (id, first_name, last_name) values (9, 'Petra', 'Gillson');
insert into authors (id, first_name, last_name) values (10, 'Charlena', 'Jammes');
insert into authors (id, first_name, last_name) values (11, 'Milly', 'Beardsdale');
insert into authors (id, first_name, last_name) values (12, 'Frederic', 'McCaw');
insert into authors (id, first_name, last_name) values (13, 'Westleigh', 'Willgoss');
insert into authors (id, first_name, last_name) values (14, 'Franz', 'Dickings');
insert into authors (id, first_name, last_name) values (15, 'Shelly', 'MacCahey');

insert into books (id, price, price_old, title, author_id) values (1, 4263, 7873, 'Geba', 97);
insert into books (id, price, price_old, title, author_id) values (2, 2012, 3820, 'Browsecat', 29);
insert into books (id, price, price_old, title, author_id) values (3, 2876, 4866, 'Skalith', 50);
insert into books (id, price, price_old, title, author_id) values (4, 2316, 9266, 'Flipstorm', 31);
insert into books (id, price, price_old, title, author_id) values (5, 2195, 6852, 'Wikizz', 77);
insert into books (id, price, price_old, title, author_id) values (6, 1747, 9458, 'Mymm', 4);
insert into books (id, price, price_old, title, author_id) values (7, 2873, 6714, 'Gigaclub', 41);
insert into books (id, price, price_old, title, author_id) values (8, 3333, 9787, 'Thoughtstorm', 39);
insert into books (id, price, price_old, title, author_id) values (9, 3147, 3406, 'Voonte', 8);
insert into books (id, price, price_old, title, author_id) values (10, 832, 9061, 'Avavee', 60);
insert into books (id, price, price_old, title, author_id) values (11, 1761, 7270, 'Kwideo', 37);
insert into books (id, price, price_old, title, author_id) values (12, 4996, 2505, 'Feedspan', 10);
insert into books (id, price, price_old, title, author_id) values (13, 3492, 3519, 'Wordware', 35);
insert into books (id, price, price_old, title, author_id) values (14, 1769, 1235, 'Ainyx', 85);
insert into books (id, price, price_old, title, author_id) values (15, 3537, 4683, 'Vimbo', 58);